In [ ]:
# Q-1 What is a parameter?
#ANS- A parameter is a variable or constant that defines certain characteristics or conditions in a specific system, process, or model.
#Parameters are typically used to set constraints, limit values, or influence the behavior of a system.
#Here are a few contexts where "parameter" is commonly used:
#Mathematics/Statistics: A parameter is a numerical factor that defines a particular characteristic of a function, distribution, or system.
#For example, in a normal distribution, the mean and standard deviation are parameters that define the shape of the distribution.
#Programming/Software Development: In programming, a parameter is a variable used in a function or method definition. It accepts a value when the function is called

In [ ]:
#Q-2 What is correlation?
#What does negative correlation mean?

In [ ]:
#ANS-Correlation refers to the statistical relationship or association between two or more variables.
#It describes whether and how strongly the variables move together. In other words, correlation indicates if changes in one variable are related to changes in another.
#A positive correlation means that as one variable increases, the other tends to increase as well.
#A negative correlation means that as one variable increases, the other tends to decrease.

#Negative correlation refers to a relationship between two variables where, as one variable increases,
#the other variable decreases, and vice versa. This type of relationship is often referred to as an inverse relationship.

#Key Features of Negative Correlation:
#If one variable goes up, the other tends to go down.
#The correlation coefficient (r) for a negative correlation ranges between -1 and 0

In [3]:
#3-Define machine learning.what are the main components in machine learning?
#ANS-Machine learning is a subset of artificial intelligence (AI) that focuses on building algorithms and statistical models
#that allow computers to learn from and make predictions or decisions based on data,without being explicitly programmed to perform specific tasks.
# Main Components of Machine Learning
#Data (Training and Test data)
#Algorithms (Methods to extract patterns)
#Model (Trained representation of the data)
#Features (Input variables or characteristics)
#Learning Process (Supervised, Unsupervised, Reinforcement)
#Evaluation Metrics (Measuring model performance)
#Optimization (Improving model's predictions)
#Hyperparameters (Settings influencing training)

In [ ]:
#Q-4 How does loss value help in determining whether the model is good or not?
#ANS-The loss value (also known as the loss function or cost function) is a key indicator used to measure how well a machine
#learning model is performing. It quantifies the difference between the model
#predictions and the actual values (true labels) in the data. The goal of training a model is to minimize this loss,
#indicating that the model is making predictions that are closer to the true values.

#Loss indicates model performance: Lower loss suggests better predictions.
#Guides optimization: During training, minimizing loss improves model accuracy.
#Reveals overfitting or underfitting: Loss on training vs. test data highlights generalization issues.
#Assists in model selection and hyperparameter tuning: Comparing models or adjusting settings is done based on loss values.
#Interpretable feedback: Provides clear guidance on whether the model is performing well or needs improvement.

In [ ]:
#Q-5 What are continuous and categorical variables?
#ANS-Continuous Variables and Categorical Variables are two types of data that differ in how they can be measured and represented.
# 1. Continuous Variables:
# Definition: Continuous variables are quantitative variables that can take any value within a given range.
#They can represent measurements and can be divided into smaller increments.
# Characteristics:
# They are numeric and can have an infinite number of possible values.
#Examples: Height, weight, temperature, age, time, distance.Can take decimal values (e.g., 2.5, 3.14).Often measured on a continuous scale.
#Example:The temperature in a room can be 20.5°C, 20.55°C, or 20.555°C, and so on, showing an infinite number of possible values within a range.
#2. Categorical Variables:
#Definition: Categorical variables, also known as qualitative variables, represent data that can be divided into distinct categories or groups.
#The values are not numeric but represent different classes or categories.
#Characteristics:
#They can take on a limited, fixed number of categories.
#Nominal: Categories with no inherent order (e.g., colors, countries, or brands).
#rdinal: Categories with a clear, meaningful order but the distance between them isn’t consistent (e.g., education levels
#like "High School," "Bachelor's," and "Master's").

In [ ]:
#Q-6How do we handle categorical variables in Machine learning?What are the common techniques?
#ANS-Handling categorical variables is an essential part of preprocessing data for machine learning.
#Most machine learning algorithms require numerical input, so categorical variables (which represent distinct classes or categories)
#need to be converted into a format that the model can understand.

#1. Label Encoding:
#What it is: Label encoding involves converting each category into a unique integer. Each category is assigned a number, usually starting from 0.
#When to use: Label encoding is useful when the categorical variable has a natural order or ranking (ordinal variable). 
#For example, categories like Low, Medium, and High can be represented as 0, 1, and 2.
# Example
Category: ["Low", "Medium", "High"]
Encoded: [0, 1, 2]


#2 One-Hot Encoding:
#What it is: One-hot encoding transforms each category of a variable into a separate binary (0 or 1) column. For each category,
#a new column is created, and if the category is present in a row, it gets a value of 1; otherwise, it gets a value of 0.
#When to use: One-hot encoding is used when the categorical variable is nominal, i.e., the categories have no inherent order.
# Example

Category: ["Red", "Blue", "Green"]
One-Hot Encoded:
Red   | Blue | Green
-------------------
1     | 0    | 0
0     | 1    | 0
0     | 0    | 1


#Advantages: It avoids introducing any ordinal relationships between categories, which is important for nominal data.
#Limitations: It increases the dimensionality of the dataset, which can lead to sparse data and potential performance issues,
#especially with many unique categories.


In [ ]:
#Q-7What do you mean by training and testing a dataset?
#ANS-In machine learning, the terms training and testing a dataset refer to the processes of training a model on one part of
#the data and evaluating its performance on another, separate part of the data.
#1 Training a Dataset:
#What it means: Training a model involves using a subset of the data (called the training set) to teach the model how to make predictions or classifications.
#Process:
#The training dataset is used to "teach" the model by feeding it input data (features) along with the correct output (labels or targets). 
#The model learns the relationships between the inputs and outputs by adjusting its parameters (e.g., weights in a neural network or splits in a decision tree) to minimize the error or loss.
#Goal: The goal of training is for the model to learn the underlying patterns and relationships in the data so that 
#it can make accurate predictions on new, unseen data.

#2. Testing a Dataset:
#What it means: Testing the model involves using a separate subset of the data, known as the test set, to evaluate how well the model performs after it has been trained.
#Process:
#Once the model is trained on the training data, it is evaluated on the test data (which it has not seen during training).
#The test set serves as a proxy for unseen data and helps to assess how well the model generalizes beyond the specific examples it was trained on.
#Goal: The goal of testing is to measure the generalization ability of the model — how well it can perform on new,
#previously unseen data.

In [12]:
#Q -8 OR Q-23 ARE SAME.
#Q-8 What is sklearn.preprocessing?
#ANS-sklearn.preprocessing is a module in scikit-learn (a popular Python library for machine learning) that provides a
#variety of tools for data preprocessing. Preprocessing refers to the steps performed on raw data before feeding it into machine learning models. 
#This module contains methods for transforming features to make them suitable for machine learning algorithms.
# Encoding Categorical Features
#LabelEncoder: Converts categorical labels (target variables) into numerical values. It is mainly used for target variables 
#in classification tasks.
#For example, it converts labels like ['cat', 'dog', 'fish'] to [0, 1, 2].

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_encoded = le.fit_transform(y)

In [ ]:
#Q-9What is a test set?
#ANS-A test set is a subset of your dataset that is used to evaluate the performance of a machine learning model after it 
#has been trained. The key purpose of the test set is to assess how well the model generalizes to unseen data, providing an
#indication of how the model is likely to perform on new, real-world data.

#Key Characteristics of a Test Set:
#Not Used in Training: The test set is completely separate from the data used to train the model. The model never sees or
#learns from the test set during the training process. This ensures an unbiased evaluation.
#Evaluates Generalization: The main goal of the test set is to measure how well the model can generalize to new, unseen data.
#This is important because the ultimate goal of a machine learning model is to make accurate predictions on data it hasn't encountered before.
#Represents Real-World Data: Since the test set is treated as "new" data, it simulates how the model will perform when 
#deployed in real-world scenarios, where the data it encounters may differ from the training data.
#Contains Labels: The test set typically includes true labels (the correct answers or target values) for supervised learning
#tasks, which are needed to evaluate the model's predictions and compute performance metrics.

In [13]:
#Q-10-How do we split data for model fitting (training and testing) in python?
#How do you approach a Machine learning problem?
#ANS-In Python, particularly using scikit-learn (a popular machine learning library), splitting data into training and testing
#sets is done using the train_test_split function from the model_selection module. This function randomly splits the data 
#into two subsets: one for training the model and one for evaluating it.
# Example

from sklearn.model_selection import train_test_split
import numpy as np

# Example data
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])  # Features
y = np.array([1, 2, 3, 4, 5])  # Target variable

# Split the data into training and testing sets (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Training Features:", X_train)
print("Test Features:", X_test)
print("Training Target:", y_train)
print("Test Target:", y_test)


Training Features: [[ 9 10]
 [ 5  6]
 [ 1  2]
 [ 7  8]]
Test Features: [[3 4]]
Training Target: [5 3 1 4]
Test Target: [2]


In [ ]:
#How do you approach a Machine Learning problem?
#Approaching a machine learning problem typically involves a series of systematic steps to ensure that you understand th
#problem, preprocess the data correctly, build a good model, and evaluate its performance effectively. Here’s a common step-by-step approach.

#1-Define the problem and understand the objective.
#2-Collect and prepare the data: Perform data cleaning, transformation, and feature engineering.
#3-Split the data into training and testing sets.
#4-Choose the model based on the problem type (classification, regression, clustering, etc.).
#5-Train the model on the training data.
#6-Evaluate the model on the test data using appropriate metrics.
#7-Tune the model using hyperparameter optimization and cross-validation.
#8-Deploy and monitor the model once it’s ready for real-world use.

In [ ]:
#Q-11Why do we have to perform EDA before fitting a model to the data?
#ANS- Performing Exploratory Data Analysis (EDA) before fitting a model to the data is a critical step in the machine learning
#pipeline. EDA helps you better understand the characteristics of your dataset, which guides the subsequent steps in the
#modeling process. Here's why EDA is essential.
#Performing Exploratory Data Analysis (EDA) is crucial because it helps you:

#1-Understand the data structure, distribution, and relationships between features and the target.
#2-Identify data quality issues like missing values, outliers, and inconsistencies.
#30Prepare the data by transforming, scaling, and encoding features as necessary.
#4-Decide on the right model based on the nature of the data (e.g., regression, classification).
#5-Discover new features or interactions that may improve the model.
#6-Build trust in the model by understanding the data deeply before applying machine learning algorithms.

In [ ]:
#Q-12What is correlation?
#Correlation is a statistical measure that describes the strength and direction of the relationship between two variables.
#It tells us how one variable changes in relation to another. If two variables tend to increase or decrease together, 
#they are said to be correlated.

#Types of Correlation:
#1- Positive Correlation: When two variables increase or decrease together in the same direction. For example, as the temperature increases, the sales of ice cream may also increase.

#Example: Height and weight often show a positive correlation—taller people tend to weigh more.
#2- Negative Correlation: When one variable increases while the other decreases, or vice versa. In other words, they move in opposite directions.
#Example: The amount of time spent on exercise and body fat percentage might show a negative correlation — as the time spent on exercise increases, the body fat percentage may decrease.

#3- No Correlation: When there is no discernible relationship between the two variables, meaning changes in one variable 
#do not predict changes in the other.
#example: The number of books a person reads and the number of cars they own might show no correlation.

In [ ]:
#Q-13What does neagative correlation mean?
#ANS-Negative correlation refers to a relationship between two variables in which one variable increases as the other
#decreases, or vice versa. Essentially, when one variable goes up, the other tends to go down, and when one variable goes down,
#the other tends to go up. This kind of relationship is called inverse correlation.

#Key Points:
#Inverse relationship: Negative correlation means that the variables move in opposite directions.
#Correlation coefficient: A negative correlation is represented by a correlation coefficient(r)
#that falls between -1 and 0. The closer the value is to -1, the stronger the negative correlation.
#Examples of Negative Correlation:
#1-Exercise and body fat percentage  2-Price and demand  3-Temperature and heating costs.

In [14]:
#14-How can you find the correlation between variables in python?
#ANS-To find the correlation between variables in Python, you can use libraries such as Pandas, NumPy, or SciPy.
#Here's how to compute correlation using these libraries.
#. Using Pandas
#Pandas provides a simple and efficient way to compute correlation using the .corr() method, which computes the Pearson 
#correlation by default.
import pandas as pd

# Example data
data = {'Height': [150, 160, 170, 180, 190],
        'Weight': [50, 60, 70, 80, 90]}

# Create a DataFrame
df = pd.DataFrame(data)

# Calculate correlation between the variables
correlation = df.corr()

# Print the correlation matrix
print(correlation)


<ipython-input-14-76c8718b0aa1>:7: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


        Height  Weight
Height     1.0     1.0
Weight     1.0     1.0


In [ ]:
#Q-15What is causation?Explain difference between correlation and causation with an example.
#ANS-Causation refers to a cause-and-effect relationship between two variables, where one variable directly influences the
#other. In other words, a change in one variable leads to a change in the other variable, and the effect can be traced back to the cause.

#Difference Between Correlation and Causation:
#1. Correlation:
#Definition: Correlation measures the association between two variables. If two variables are correlated, 
#it means that they tend to move together, but it does not imply that one is causing the other to change.
#Nature of relationship: Correlation can be either positive or negative, but it does not specify a direct cause-and-effect relationship.
#Interpretation: Correlation tells us how two variables are related but not why.
#2. Causation:
#Definition: Causation is a direct cause-and-effect relationship where one variable directly influences or causes the change in another variable.
#Nature of relationship: Causation specifies that one variable causes another to change.
#Interpretation: Causation tells us not just how two variables are related, but also why and how one causes the other to change.

In [ ]:
#Q-16 What is an Optimizer? What are different types of optimizers? Explain each with an example.
#ANS-An optimizer in machine learning is an algorithm or method used to minimize or maximize an objective function,
#such as a loss function (for training models), by adjusting the parameters (weights and biases) of the model. 

#Different Types of Optimizers
#There are several types of optimizers, each with different approaches to updating the model parameters.
#Below are the most commonly used optimizers in machine learning.
#1. Gradient Descent (GD)
#Description: Gradient Descent is the simplest optimization algorithm. It calculates the gradient of the loss function with
#respect to each parameter and updates the parameters in the opposite direction of the gradient. 
#The step size is determined by the learning rate.
#Example: If you're training a linear regression model, gradient descent will adjust the weights w of the linear equation
#y=wx+b to minimize the mean squared error (MSE) loss.
#Types:
#Batch Gradient Descent: Uses the entire dataset to compute the gradient.
#Stochastic Gradient Descent (SGD): Uses one random sample to compute the gradient at each step.
#Mini-batch Gradient Descent: Uses a small random batch of samples to compute the gradient.


In [15]:
#Q-17 What is sklearn.linear_model?
#ANS- sklearn.linear_model is a module in scikit-learn, a popular machine learning library in Python, that contains various
#linear models for regression and classification tasks. These models are based on the principles of linear relationships 
#between input variables and the target variable.
#Key Models in sklearn.linear_model:
#Linear Regression (LinearRegression)
#Purpose: Used for regression tasks where the relationship between the independent variables (features) and the 
#dependent variable (target) is assumed to be linear.
#Example: Predicting house prices based on features like size, location, etc.
#Example Usage:

from sklearn.linear_model import LinearRegression

# Example data
X = [[1], [2], [3], [4]]  # Features (input)
y = [1, 2, 3, 4]  # Target (output)

model = LinearRegression()
model.fit(X, y)

print(model.predict([[5]]))  # Predict for new data

[5.]


In [ ]:
#Q-18-What does model.fit()do?What arguementsmust be given?
#ANS-#In machine learning, the model.fit() method is used to train a model on the provided dataset. When you call model.fit(),
#you're fitting the model to the data by adjusting the model's parameters (such as weights and biases in the case of linear
#models or neural networks). 

#What Does model.fit() Do?
#Learning from Data: It takes the training data and the corresponding labels (for supervised learning) and finds the best-fit parameters that minimize the error (e.g., loss function).
#Model Training: The model's internal parameters (e.g., coefficients in linear regression, weights in neural networks) are adjusted using an optimization algorithm like gradient descent to minimize the error.
#Fitting Process: The process of fitting is essentially training, where the model learns the relationship between features (input) and the target (output).

#Arguments for model.fit()
#The arguments you need to pass to model.fit() depend on the type of model and task you are dealing with (e.g., regression or classification). Generally, two main arguments are required:
#X (features): This is the input data. It consists of the features or independent variables that will be used to predict the target variable. It is typically a 2D array or DataFrame, where rows represent data points (samples) and columns represent features.
#Shape: (n_samples, n_features) — n_samples is the number of data points, and n_features is the number of features or input variables.
#y (target): This is the output or dependent variable. It contains the labels or target values that correspond to the input data. For supervised learning, this is what you want the model to predict.
#Shape: (n_samples,) for a 1D array of labels in classification or regression tasks, or (n_samples, n_targets) for multi-output tasks.

In [16]:
#Q-19 What does model.predict()do?What arguements must be given?
#ANS-The model.predict() method in machine learning is used to make predictions after a model has been trained (fitted).

#What Does model.predict() Do?
#Prediction: After the model has been trained using model.fit(), you can call model.predict() to get the model’s output for 
#new data points. It applies the learned parameters (like coefficients in linear models or weights in neural networks) to the input data and produces predictions.
#Inference: It makes an inference based on the input features, which means it predicts what the tthe target variable (output)
#would be for unseen data, based on the relationships the model has learned during training.

#Arguments for model.predict()
#The main argument you need to provide to model.predict() is the input data for which you want the model to make predictions.
#This input data must have the same structure and format as the data used to train the model.
#X (features):
#This is the new data you want the model to predict on. It should be in the same format as the data passed to model.fit().
#Shape: (n_samples, n_features) — n_samples is the number of new samples, and n_features is the number of features. 
#Each sample represents a data point, and each feature corresponds to an attribute or characteristic of that data point.
#The number of features in the prediction data must match the number of features used during training (i.e., 
#the number of columns in X used for training should be the same as the number of columns in the data passed to pre

#Here is an example using linear regression to illustrate how model.predict() works:

from sklearn.linear_model import LinearRegression

# Training data (features and target)
X_train = [[1], [2], [3], [4]]
y_train = [1, 2, 3, 4]

# Create and train the model
model = LinearRegression()
model.fit(X_train, y_train)

# New data for prediction
X_new = [[5], [6]]

# Make predictions on the new data
predictions = model.predict(X_new)

print(predictions)


[5. 6.]


In [ ]:
#Q-20 What are continuous and categorical variables?
#ANS-In statistics and machine learning, continuous and categorical variables are two types of data based on the nature of
#the values they can take and how those values are interpreted.
#1. Continuous Variables
#Definition: Continuous variables are numeric variables that can take any value within a range.
#These values are typically real numbers and can have decimal places, representing quantities or measurements.
#Examples:
#Height of a person (e.g., 170.5 cm) ,Temperature (e.g., 36.6°C) ,Weight (e.g., 68.2 kg) ,Income (e.g., $45,000.50)
#Characteristics:
#Values are ordered and measurable.
#They can take infinitely many values within a specified range.
#Often associated with physical measurements or quantities.
#Use in Machine Learning:
#Used directly in most machine learning models without transformation.
#Examples include features like age, salary, or temperature.

#2. Categorical Variables
#Definition: Categorical variables represent discrete groups or categories. The values of these variables are labels
#or names that signify membership in a particular group.
#Examples: Gender (e.g., Male, Female, Other), Color (e.g., Red, Blue, Green), Type of vehicle (e.g., Car, Truck, Bike)
#Education level (e.g., High School, Bachelor’s, Master’s), Types of Categorical Variables:

#Nominal: Categories have no inherent order.
#Example: Colors (Red, Green, Blue), Gender (Male, Female, Other)
#Ordinal: Categories have a meaningful order or ranking.
#Example: Education level (High School < Bachelor’s < Master’s)
#Characteristics:
#Values are distinct groups or labels.
#They cannot be measured on a continuous scale.
#Can be numeric (e.g., 0 for Male, 1 for Female) but these numbers do not have mathematical significance.
#Use in Machine Learning:
#Need to be converted into numeric representations (e.g., one-hot encoding or label encoding) before being used in most algorithms.

In [ ]:
#Q-21 What is feature scaling?How does it help in Machine learning?
#ANS-Feature Scaling is a preprocessing technique used in machine learning to standardize or normalize the range of 
#independent variables (features). The purpose is to ensure that all features have a comparable scale, preventing features
#with larger ranges from dominating the model's learning process.

#It helps in machine learning.
#In many machine learning algorithms, the magnitude of feature values can significantly impact model performance. 
#Here's why scaling is important:
#Equal Contribution:
#Features with larger scales (e.g., salary in thousands) can dominate features with smaller scales (e.g., age in years), leading to biased models.
#Feature scaling ensures all features contribute equally.
#Improved Convergence:

#For optimization algorithms (like Gradient Descent), having features on similar scales accelerates convergence and prevents numerical instability.
#Sensitive Models:
#Certain machine learning algorithms are sensitive to feature magnitudes. These include:
#Distance-based algorithms: K-Nearest Neighbors (KNN), Support Vector Machines (SVMs), and clustering (e.g., K-Means) rely on distances like Euclidean distance, which is affected by feature scales.
#Gradient-based algorithms: Linear Regression, Logistic Regression, Neural Networks, etc., benefit from scaled features for better performance.
#Decision Tree-based models (e.g., Random Forest, Gradient Boosted Trees) are generally not affected by feature scaling

In [2]:
#Q-22 How do we perform scaling in python?
#ANS-Scaling in Python typically involves transforming numerical data to a specific range or distribution, making it more 
#suitable for machine learning models or other analysis. This is commonly done using libraries like scikit-learn, 
#which provides utilities for scaling data. Here’s a quick overview of the most popular scaling methods and their implementations.

#1. Standardization (Z-Score Scaling)
#Transforms the data to have a mean of 0 and a standard deviation of 1.

from sklearn.preprocessing import StandardScaler

# Example data
data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)

print(scaled_data)

[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


In [3]:
#2. Min-Max Scaling
#Transforms data to a fixed range, usually [0, 1].

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(data)

print(scaled_data)

[[0.  0.  0. ]
 [0.5 0.5 0.5]
 [1.  1.  1. ]]


In [4]:
#Q-24How do we split data for model fitting(training and testing) in python?
#ANS-In Python, particularly using scikit-learn (a popular machine learning library), splitting data into training and testing
#sets is done using the train_test_split function from the model_selection module. This function randomly splits the data 
#into two subsets: one for training the model and one for evaluating it.
# Example

from sklearn.model_selection import train_test_split
import numpy as np

# Example data
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])  # Features
y = np.array([1, 2, 3, 4, 5])  # Target variable

# Split the data into training and testing sets (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Training Features:", X_train)
print("Test Features:", X_test)
print("Training Target:", y_train)
print("Test Target:", y_test)


Training Features: [[ 9 10]
 [ 5  6]
 [ 1  2]
 [ 7  8]]
Test Features: [[3 4]]
Training Target: [5 3 1 4]
Test Target: [2]


In [9]:
#Q-25Explain data encoding?
#ANS-Data encoding is the process of converting categorical or textual data into numerical formats that machine learning
#models can understand and process. Since most ML models work with numerical data, encoding ensures that categorical features
#(e.g., "red," "blue," "green") are transformed into a suitable format for analysis while preserving the information.

#Types of Data Encoding
#1- Label Encoding
#Assigns a unique integer to each category.
#Useful for ordinal data (where categories have a natural order).
#Example:
from sklearn.preprocessing import LabelEncoder

data = ['red', 'blue', 'green']
encoder = LabelEncoder()
encoded_data = encoder.fit_transform(data)

print(encoded_data) 

[2 0 1]


In [11]:
#2-One-Hot Encoding
#Converts each category into a binary column, with a 1 indicating the presence of that category.
#Commonly used for nominal data (categories with no inherent order).
#Example:
from sklearn.preprocessing import OneHotEncoder

data = [['red'], ['blue'], ['green']]
encoder = OneHotEncoder()
encoded_data = encoder.fit_transform(data).toarray()

print(encoded_data)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [12]:
#3-Ordinal Encoding
#Similar to label encoding but allows manual mapping for ordinal relationships.
#Example:
from sklearn.preprocessing import OrdinalEncoder

data = [['low'], ['medium'], ['high']]
encoder = OrdinalEncoder(categories=[['low', 'medium', 'high']])
encoded_data = encoder.fit_transform(data)

print(encoded_data)

[[0.]
 [1.]
 [2.]]
